# Generated by Django 2.2.2 on 2019-06-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
    ]
