# Generated by Django 2.2.2 on 2019-06-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
