# Generated by Django 2.2.2 on 2019-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.IntegerField(),
        ),
    ]
