# Generated by Django 2.2.2 on 2019-06-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190612_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='batch_date',
            field=models.DateTimeField(),
        ),
    ]
